### ISSUE TITLE
Displaying groupimage in postbit and in profile page

### ISSUE THREAD

**Issue by Neurovert** [dragonexpert/MyBB-Theme-Variables#2]
Hi,

Is it possible to use your plugin to determine postbit_groupimage and member_profile_groupimage template "viewability" per usergroup? I'd like to keep one default theme for all users but restrict groupimages displaying to be non-viewable for guests and basic registered users.

Any ideas?

Thanks.

**Comment by dragonexpert** [comment]
Should be possible.  If you wrap the variable that displays the group image in a variable you create here you can allow access based on usergroup.  If you still can't get it, let me know and tomorrow I'll dive into the templates to look exactly what it will say.  Right now I just got home from my brother's graduation.

**Comment by Neurovert** [comment]
K' I've got it :)

![2015-06-14_09-05-58](https://cloud.githubusercontent.com/assets/7596867/8147613/a3202108-1274-11e5-9f6d-f10a91476eea.png)
